name: Delete Test Stack on merged PR close

on:
  pull_request:
    types:
      - closed

  cleanup-on-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    permissions:
      contents: read
      
    steps:
      - name: configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - name: Delete Test Stack
        run: |
          stack_name="pr-test-stack-${{github.event.pull_request.number}}"
          aws cloudformation delete-stack --stack-name $stack_name


